# frozen_string_literal: true

require "webhookdb/postgres/model"

require "webhookdb/message"

class Webhookdb::Message::Body < Webhookdb::Postgres::Model(:message_bodies)
  plugin :timestamps
  plugin :text_searchable, terms: [:content]

  many_to_one :delivery, class: "Webhookdb::Message::Delivery"
end

# Table: message_bodies
# ----------------------------------------------------------------------------------------------------
# Columns:
#  id          | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  content     | text    | NOT NULL
#  mediatype   | text    | NOT NULL
#  delivery_id | integer | NOT NULL
# Indexes:
#  message_bodies_pkey              | PRIMARY KEY btree (id)
#  message_bodies_delivery_id_index | btree (delivery_id)
# Foreign key constraints:
#  message_bodies_delivery_id_fkey | (delivery_id) REFERENCES message_deliveries(id) ON DELETE CASCADE
# ----------------------------------------------------------------------------------------------------
