# frozen_string_literal: true

require "webhookdb/postgres/model"

class Webhookdb::Organization < Webhookdb::Postgres::Model(:organizations)
  plugin :timestamps
  plugin :soft_deletes

  one_to_many :memberships, class: "Webhookdb::OrganizationMembership"
  one_to_many :service_integrations, class: "Webhookdb::ServiceIntegration"

  def before_create
    self.key ||= Webhookdb.to_slug(self.name)
    super
  end

  def before_save
    self.key ||= Webhookdb.to_slug(self.name)
    super
  end

  def self.create_if_unique(params)
    self.db.transaction(savepoint: true) do
      return Webhookdb::Organization.create(name: params[:name])
    end
  rescue Sequel::UniqueConstraintViolation
    return nil
  end

  def cli_editable_fields
    return ["name", "billing_email"]
  end
end

# Table: organizations
# --------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                       | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at               | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at               | timestamp with time zone |
#  soft_deleted_at          | timestamp with time zone |
#  name                     | text                     | NOT NULL
#  key                      | text                     |
#  readonly_connection_url  | text                     |
#  readwrite_connection_url | text                     |
#  admin_connection_url     | text                     |
# Indexes:
#  organizations_pkey     | PRIMARY KEY btree (id)
#  organizations_key_key  | UNIQUE btree (key)
#  organizations_name_key | UNIQUE btree (name)
# Referenced By:
#  organization_memberships | organization_memberships_organization_id_fkey | (organization_id) REFERENCES organizations(id)
#  service_integrations     | service_integrations_organization_id_fkey     | (organization_id) REFERENCES organizations(id)
# --------------------------------------------------------------------------------------------------------------------------
