# frozen_string_literal: true

require "webhookdb/postgres/model"

class Webhookdb::OrganizationRole < Webhookdb::Postgres::Model(:organization_roles)
  def self.admin_role
    return Webhookdb.cached_get("role_admin") do
      self.find_or_create_or_find(name: "admin")
    end
  end

  one_to_many :organization_memberships, class: "Webhookdb::OrganizationMembership"
end

# Table: organization_roles
# ---------------------------------------------------------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    | NOT NULL
# Indexes:
#  organization_roles_pkey     | PRIMARY KEY btree (id)
#  organization_roles_name_key | UNIQUE btree (name)
# Referenced By:
#  organization_memberships | organization_memberships_role_id_fkey | (role_id) REFERENCES organization_roles(id)
# ---------------------------------------------------------------------------------------------------------------
