# frozen_string_literal: true

require "webhookdb/postgres/model"

class Webhookdb::Role < Webhookdb::Postgres::Model(:roles)
  def self.admin_role
    return Webhookdb.cached_get("role_admin") do
      self.find_or_create_or_find(name: "admin")
    end
  end

  many_to_many :customers,
               class: "Webhookdb::Customer",
               join_table: :roles_customers
end

# Table: roles
# --------------------------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    | NOT NULL
# Indexes:
#  roles_pkey     | PRIMARY KEY btree (id)
#  roles_name_key | UNIQUE btree (name)
# Referenced By:
#  roles_customers | roles_customers_role_id_fkey | (role_id) REFERENCES roles(id)
# --------------------------------------------------------------------------------
