# frozen_string_literal: true

class Webhookdb::SavedQuery < Webhookdb::Postgres::Model(:saved_queries)
  plugin :timestamps
  plugin :text_searchable, terms: [:organization, :created_by]

  CLI_EDITABLE_FIELDS = ["description", "sql", "public"].freeze
  INFO_FIELDS = {
    "id" => :opaque_id,
    "description" => :description,
    "public" => :public,
    "run_url" => :run_url,
    "sql" => :sql,
  }.freeze
  DOCS_URL = "https://docs.webhookdb.com/docs/integrating/saved-queries.html"

  many_to_one :organization, class: "Webhookdb::Organization"
  many_to_one :created_by, class: "Webhookdb::Customer"

  alias public? public
  def private? = !self.public?

  def before_create
    self[:opaque_id] ||= Webhookdb::Id.new_opaque_id("svq")
    super
  end

  def run_url = "#{Webhookdb.api_url}/v1/saved_queries/#{self.opaque_id}/run"
end

# Table: saved_queries
# ------------------------------------------------------------------------------------------------------
# Columns:
#  id              | integer                  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  created_at      | timestamp with time zone | NOT NULL DEFAULT now()
#  updated_at      | timestamp with time zone |
#  organization_id | integer                  | NOT NULL
#  created_by_id   | integer                  |
#  opaque_id       | text                     | NOT NULL
#  description     | text                     | NOT NULL
#  sql             | text                     | NOT NULL
#  public          | boolean                  | NOT NULL DEFAULT false
#  text_search     | tsvector                 |
# Indexes:
#  saved_queries_pkey                  | PRIMARY KEY btree (id)
#  saved_queries_opaque_id_key         | UNIQUE btree (opaque_id)
#  saved_queries_organization_id_index | btree (organization_id)
# Foreign key constraints:
#  saved_queries_created_by_id_fkey   | (created_by_id) REFERENCES customers(id) ON DELETE SET NULL
#  saved_queries_organization_id_fkey | (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
# ------------------------------------------------------------------------------------------------------
